name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4


    - name: Generate fake certificates
      run: |
        ./scripts/generate_cert.sh
        

    - name: Test with certificates
      run: |
        python -c "import ssl; print('SSL version:', ssl.OPENSSL_VERSION)"
        ls -l certs/
        

    - name: Run tests
      run: pytest tests/