name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
          pip install -e .  # Установка проекта в режиме разработки

      - name: Run tests
        run: pytest tests/ --verbose

      - name: Generate certificates
        run: |
          bash scripts/generate_cert.sh
      - name: Install package in editable mode
        run: pip install -e .